name: Build AlgolTool Binary (.exe) on Windows and Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g. v1.2.0)'
        required: true

jobs:
  build-native-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GraalVM for Windows
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.1'
          java-version: '21'
          distribution: 'graalvm-community'
          components: 'native-image'

      - name: Build Algol and AlgolTool JAR
        working-directory: ./MockToolsParent
        run: mvn clean install -DskipTests -pl ../Algol,../AlgolTool -am

      - name: Process AOT classes
        working-directory: ./AlgolTool
        run: mvn spring-boot:process-aot

      - name: Create native .exe from AOT classes
        working-directory: ./AlgolTool
        shell: pwsh
        run: |
          native-image --no-fallback --enable-https `
            -H:Name=algol-tool `
            -H:Class=io.github.mockup.algoltool.AlgolToolApplication `
            -cp target/classes;target/generated-aot/classes `
            algol-tool.exe

      - name: Prepare files for GitHub Pages
        shell: pwsh
        run: |
          $dest = "publish/algol-tool/${{ github.event.inputs.version }}"
          mkdir $dest -Force
          Copy-Item AlgolTool/target/algol-tool-*.jar "$dest/algol-tool.jar"
          Copy-Item AlgolTool/algol-tool.exe "$dest/algol-tool.exe"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish
