name: Build AlgolTool Binary and Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g. v1.2.0)'
        required: true

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK with GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.1'
          java-version: '21'
          distribution: 'graalvm-community'
          components: 'native-image'

      - name: Build Algol and AlgolTool
        run: mvn clean install -pl ../Algol,../AlgolTool -am
        working-directory: ./MockToolsParent

      - name: Create native binary (.exe)
        run: |
          cd AlgolTool
          native-image --no-fallback --enable-https --static \
            -jar target/algol-tool-*-shaded.jar \
            algol-tool.exe

      - name: Prepare files for GitHub Pages
        run: |
          mkdir -p publish/algol-tool/${{ github.event.inputs.version }}
          cp AlgolTool/target/algol-tool-*.jar publish/algol-tool/${{ github.event.inputs.version }}/algol-tool.jar
          cp AlgolTool/algol-tool.exe publish/algol-tool/${{ github.event.inputs.version }}/algol-tool.exe

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish
