name: Build AlgolTool Binary (.exe) on Windows and Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g. v1.2.0)'
        required: true

jobs:
  build-native-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GraalVM for Windows
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.1'
          java-version: '21'
          distribution: 'graalvm-community'
          components: 'native-image'

      - name: Build with Native Profile
        working-directory: ./MockToolsParent
        run: mvn clean install -DskipTests -Pnative -pl ../Algol,../AlgolTool -am

      - name: Prepare files for GitHub Pages
        shell: pwsh
        run: |
          $dest = "publish/algol-tool/${{ github.event.inputs.version }}"
          mkdir $dest -Force
          Copy-Item AlgolTool/target/algol-tool-*.jar "$dest/algol-tool.jar"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish
